### ISSUE TITLE
Add Italian language

### ISSUE THREAD

**Issue by bovirus** [andr7e/DeviceInfoHW_translations#40]
@andr7e 

Can I translate the strings.xml in itlain post here and create a Pull Request?

Thanks.

**Comment by andr7e** [comment]
Thank you very much.

I have small questions for some words:
1) "sound" - at most it used for soundcard, audio reserved for audio chips, both on general tab.
2) On battery tab Cycle count = N. cicli maybe better not short form.

**Comment by bovirus** [comment]
@andr7e 

Typically Italian as string lenght is longer then English and follow some atypical ruiles. E:

Sound = Suoni 
but
Sound card = Scheda audio (in English is audio board)

"N. Cicli" if you have more space can be "Numero cicli".

As I explained I don't know what's the text space for UI and seems that Italian is longer sometimes when I can I prefer to use not always longer strings.

**Comment by andr7e** [comment]
Ok, I added translation, this is test version:

https://drive.google.com/file/d/1QZ3-R5R31RbdkvdNC5d8dMMCXWy443Z7/view?usp=sharing

In readme I use historical order.

**Comment by bovirus** [comment]
@andr7e 

I believe that for the usier the aphabetical list for languages is better.
No one is interested about historical order.

**Comment by bovirus** [comment]
@andr7e 

Thanks for new version and Italian language.
I tested the new version and  I found an issue about automatic language switch to Italian and some translation issues.

Please check here

https://github.com/andr7e/DeviceInfoHW_translations/issues/43
